### ISSUE TITLE
Hardcoding for the host name & unable to test Https site

### ISSUE THREAD

**Issue by vijayr007** [onc-healthit/ett#128]
Hardcoding in file : /master/xdrMessageFactory/src/main/java/gov/nist/healthcare/ttt/tempxdrcommunication/SimpleSOAPSender.java

**Comment by drbgfc** [comment]
See proposed fix by [vijayr007](https://github.com/vijayr007) here:
https://github.com/onc-healthit/ett/pull/131

**Comment by vijayr007** [comment]
Please help with JIRA link, to create the ticket.

**Comment by drbgfc** [comment]
Sorry for any confusion, we will create a ticket. We are fairly backed up right now, though. Thanks for the contribution!

**Comment by drbgfc** [comment]
In Jira:
ETT GG, XDR, Github PR: "Reg: XDR Test 4a , 4b - unable to test locally - hardcoding in code"
https://oncprojectracking.healthit.gov/support/browse/SITE-3533

**Comment by austinmoody** [comment]
Per https://oncprojectracking.healthit.gov/support/browse/SITE-3533 this was closed May 2023.
