### ISSUE TITLE
Conformance Info Appearing That Should Not

### ISSUE THREAD

**Issue by desai827** [onc-healthit/ett#37]
When validating the [attached](https://github.com/siteadmin/ett/files/3009271/26325_Cummings.Cecilia.J._CCDA.2.1.-.CCD.txt) file with the ETT, there are 3 additional warnings (lines 1864, 1901, 2862) that appear. The same warnings do not appear when using the Reference CCDA Service. I'm using the ONC 2015 Edition validator with the configuration C-CDA_IG_Plus_Vocab / Readme.txt

I looked in the CPT code sets and confirmed that the description matches what is in the file.

![image](https://user-images.githubusercontent.com/7298157/55018574-8632ae80-4fc9-11e9-9a5d-3dc930f21dea.png)

**Comment by drbgfc** [comment]
I have tested SITE, ETT, and the API and they all have all 3 info results mentioned. This may have to do with that the Ref Val API was updated last night (which is called by SITE and ETT). Maybe you tested with one source before the update and another after?

SITE (https://sitenv.org/sandbox-ccda/ccda-validator)

Vocabulary info:
Result Description: Display Name URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY does not exist in the code system 2.16.840.1.113883.6.12 in the configured code system name(s) CDT,SNOMED-CT,CPT
Document Xpath: /ClinicalDocument[1]/component[1]/structuredBody[1]/component[7]/section[1]/entry[1]/procedure[1]/code[1]
Document Line Number: 1864

Result Description: Display Name URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY does not exist in the code system 2.16.840.1.113883.6.12 in the configured code system name(s) CDT,SNOMED-CT,CPT
Document Xpath: /ClinicalDocument[1]/component[1]/structuredBody[1]/component[7]/section[1]/entry[2]/procedure[1]/code[1]
Document Line Number: 1901

Result Description: Display Name URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY does not exist in the code system 2.16.840.1.113883.6.96 in the configured code system name(s) LOINC,SNOMED-CT,CPT
Document Xpath: /ClinicalDocument[1]/component[1]/structuredBody[1]/component[8]/section[1]/entry[1]/organizer[1]/code[1]
Document Line Number: 2862


ETT (https://ttpedge.sitenv.org/ttp/#/validators/)

Info - Display Name URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY does not exist in the code system 2.16.840.1.113883.6.12 in the configured code system name(s) CDT,SNOMED-CT,CPT
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[7]/section[1]/entry[1]/procedure[1]/code[1]
Line number: 1864
Actual Code: 81003
Actual Display Name: URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY

Info - Display Name URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY does not exist in the code system 2.16.840.1.113883.6.12 in the configured code system name(s) CDT,SNOMED-CT,CPT
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[7]/section[1]/entry[2]/procedure[1]/code[1]
Line number: 1901
Actual Code: 81003
Actual Display Name: URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY

Info - Display Name URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY does not exist in the code system 2.16.840.1.113883.6.96 in the configured code system name(s) LOINC,SNOMED-CT,CPT
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[8]/section[1]/entry[1]/organizer[1]/code[1]
Line number: 2862
Actual Code: 24357-6
Actual Display Name: URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY


API (https://ttpds.sitenv.org:8443/referenceccdaservice/)

       {
            "description": "Display Name URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY does not exist in the code system 2.16.840.1.113883.6.12 in the configured code system name(s) CDT,SNOMED-CT,CPT",
            "type": "ONC 2015 S&CC Vocabulary Validation Conformance Info",
            "xPath": "/ClinicalDocument[1]/component[1]/structuredBody[1]/component[7]/section[1]/entry[1]/procedure[1]/code[1]",
            "validatorConfiguredXpath": "//v3:procedure/v3:templateId[@root='2.16.840.1.113883.10.20.22.4.14' and @extension='2014-06-09']/ancestor::v3:procedure[1]/v3:code[@code and not(@nullFlavor) and ancestor::v3:section[not(@nullFlavor)]]",
            "documentLineNumber": "1864",
            "actualCode": "81003",
            "actualCodeSystem": "2.16.840.1.113883.6.12",
            "actualCodeSystemName": "C4",
            "actualDisplayName": "URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY",
            "dataTypeSchemaError": false,
            "igissue": false,
            "muissue": false,
            "ds4PIssue": false,
            "schemaError": false
        },

     {
            "description": "Display Name URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY does not exist in the code system 2.16.840.1.113883.6.12 in the configured code system name(s) CDT,SNOMED-CT,CPT",
            "type": "ONC 2015 S&CC Vocabulary Validation Conformance Info",
            "xPath": "/ClinicalDocument[1]/component[1]/structuredBody[1]/component[7]/section[1]/entry[2]/procedure[1]/code[1]",
            "validatorConfiguredXpath": "//v3:procedure/v3:templateId[@root='2.16.840.1.113883.10.20.22.4.14' and @extension='2014-06-09']/ancestor::v3:procedure[1]/v3:code[@code and not(@nullFlavor) and ancestor::v3:section[not(@nullFlavor)]]",
            "documentLineNumber": "1901",
            "actualCode": "81003",
            "actualCodeSystem": "2.16.840.1.113883.6.12",
            "actualCodeSystemName": "C4",
            "actualDisplayName": "URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY",
            "dataTypeSchemaError": false,
            "igissue": false,
            "muissue": false,
            "ds4PIssue": false,
            "schemaError": false
        },

        {
            "description": "Display Name URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY does not exist in the code system 2.16.840.1.113883.6.96 in the configured code system name(s) LOINC,SNOMED-CT,CPT",
            "type": "ONC 2015 S&CC Vocabulary Validation Conformance Info",
            "xPath": "/ClinicalDocument[1]/component[1]/structuredBody[1]/component[8]/section[1]/entry[1]/organizer[1]/code[1]",
            "validatorConfiguredXpath": "//v3:organizer/v3:templateId[@root='2.16.840.1.113883.10.20.22.4.1' and @extension='2015-08-01']/ancestor::v3:organizer[1]/v3:code[@code and not(@nullFlavor) and ancestor::v3:section[not(@nullFlavor)]]",
            "documentLineNumber": "2862",
            "actualCode": "24357-6",
            "actualCodeSystem": "2.16.840.1.113883.6.96",
            "actualCodeSystemName": "SNOMED CT",
            "actualDisplayName": "URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY",
            "dataTypeSchemaError": false,
            "igissue": false,
            "muissue": false,
            "ds4PIssue": false,
            "schemaError": false
        },

**Comment by desai827** [comment]
Hi Dan,

My apologies. I was referring to our local ReferenceCCDAService implementation. The three vocab info message I specifically mentioned do not appear in our deployment. I manually reviewed the CPT reference files that we're using and confirmed that the display name does appear in the LONGULT.txt file.

Can you confirm that the same Display Name is present in your deployment?

**Comment by drbgfc** [comment]
We aren't using the file LONGULT.txt in production, intead, we are using, LONGUF.txt. From the sounds of it, one of us is out of date. We only tend to update 1x per year. So, it may be us.

Our CPT file, LONGUF.txt, does not contain the following displayName:
URINALYSIS, BY DIP STICK OR TABLET REAGENT FOR BILIRUBIN, GLUCOSE, HEMOGLOBIN, KETONES, LEUKOCYTES, NITRITE, PH, PROTEIN, SPECIFIC GRAVITY, UROBILINOGEN, ANY NUMBER OF THESE CONSTITUENTS; AUTOMATED, WITHOUT MICROSCOPY

**Comment by desai827** [comment]
Ah. The code-validator-api code_system.xlsx file states to use the LONGULT.txt file...

I've checked the files for the past 3 years and the codes are present in 2017, 2018, and 2019.

**Comment by drbgfc** [comment]
I see. Just a note, since it's a local instantiation and not directly related to the ETT UI i'd prefer this  is a https://github.com/siteadmin/reference-ccda-validator (or code validator) issue then. The ETT is a wrapper for that software. I'll leave here for now till closed though. I will have to decide which file we should be using and update either the vocab file or the spreadsheet (code_system.xlsx) then. Thanks.

**Comment by drbgfc** [comment]
A teammate of mine looked this up and we were given LONGULT.txt which was deployed in March of 2018. That is when we switched from LONGUF to LONGULT.  LONGULT was given to us by the ONC as the latest version. Do you happen to know the difference or have an argument for why we should use LONGUF instead that I can bring to the ONC? If not I would go ahead and update the spreadsheet to LONGULT. Thanks

**Comment by desai827** [comment]
Per AMA, the only difference difference between LONGULT.txt and LONGUF.txt is that the former is tab-delimited format and the latter is a fixed-field format; the content of the two should be the same.

Reviewing both files, I think it'd be best to use the LONGULT.txt format as it places a single CPT code and description per line. The LONGUF format splits the description across multiple lines.

LONGULT.txt naturally begins the description on position 9; however, the code validator documentation states position 10..

**Comment by drbgfc** [comment]
Interesting. I wonder if we can report to the AMA that these are out of sync/have different data. I will look into switching over to LONGULT as per your request (and our documentation)..

**Comment by desai827** [comment]
Thanks Dan. That should result in our local deployment matching yours.

**Comment by drbgfc** [comment]
I will have to make sure it is being loaded properly too - I'm guessing youd didn't notice any issues in your log?

**Comment by desai827** [comment]
Nope. It appeared to load correctly as far as I could tell.

**Comment by drbgfc** [comment]
Have you confirmed that you are getting errors for CPT when you should?

**Comment by desai827** [comment]
I just tested it with [this](https://github.com/siteadmin/ett/files/3034870/26325_Cummings.Cecilia.J._CCDA.2.1.-.CCD.-.Copy.txt) file where I manually truncated the displayName on line 1864 and confirmed that the appropriate vocabulary info message appears that should.

![image](https://user-images.githubusercontent.com/7298157/55417628-12e7ea00-553f-11e9-8728-7822df19c32c.png)

**Comment by drbgfc** [comment]
Ok great thanks

**Comment by drbgfc** [comment]
FYI: I have requested that the latest version of CPT (specifically LONGULT.txt) be implemented in the validator. I am waiting for the ONC to approve/provide it from AMA. It will likely be implemented in the next release, 2019 04 29

**Comment by drbgfc** [comment]
FYI this has opened a whole new can of worms in that:
-There are issues with our existing CPT loader
-The latest CPT LONGULT.txt file has displayNames as long as 16 thousand 900 characters! We defintely should not be loading those and people definitely aren't using them so this an issue with AMA. The file contains many, many instances of unusable/absurdly long display names.

The internal loader issues can be fixed no problem. AMA has to deal with the CPT format issues. I am thinking we might need to use the latest LONGUF instead of LONGULT and waiting for the AMA.

**Comment by desai827** [comment]
Oh wow. Didn't realize that but I see one now that is 16,904 characters. Crazy! For us, LONGUF vs LONGULT doesn't make a huge difference. We'll need just to know what is appropriate as the current loader specifies LONGULT.

**Comment by drbgfc** [comment]
It appears that it is a bit more complex than just using LONGUF vs LONGULT.
Looking closely LONGUF suffers the same issue it just masks it since the displayNames are split up. 
Code 81406 displayName is split into multiple lines. The last line is 81406255 meaning it's the 255th line of the display name. A display name 255 lines long is enormous. When condensed into one line, it is around 19 thousand characters. When you subtract the codes in those lines, you probably get about 17k, so it is the exact same issue.
We will have to wait for AMA to fix these issues or provide some sort of reasoning for them to exist and then decide what to do about it. Personally I can't imagine enfocing displayNames of such size or anyone ever using them.

**Comment by mrahn23** [comment]
Yeah I’ll do that this weekend when I’m hanging with dragon ;)

Sent from my iPhone

On Apr 2, 2019, at 11:50 AM, Krishna Desai <notifications@github.com<mailto:notifications@github.com>> wrote:
H

Thanks Dan. That should result in our local deployment matching yours.

**Comment by Plow74** [comment]
Just following up on this old issue - the next release (04/2021) will have an update that accommodates the loading of the tab-delimited long description CPT file, LONGULT.txt.
